import type { Idea } from './types'

// Seed extrait de statut.md (tableau consolide des idees, 2026-06-21).
// Donnees REELLES — chaque carte est une idee/chantier MangoOS, raccourcie au concept.
// Raf completera le reste : c'est le but de l'outil.

// Dates plausibles deterministes (UTC) pour eviter un seed "tout au meme instant".
const D = (m: number, d: number) => Date.UTC(2026, m - 1, d, 9, 0, 0)

export const SEED: Idea[] = [
  // --- Concepts & chantiers strategiques recents (le coeur de la decision) ---
  {
    id: 138,
    title: 'OS d\'apps personnelles — composer les apps en suite type Office',
    status: 'idea',
    model: 'opus',
    effort: 'XL',
    tags: ['concept', 'composer-os', 'architecture'],
    deps: [137],
    notes: 'Shell + contrat "MangoApp" qui heberge des apps autonomes (3 couches : design / donnee partagee / nav). Retenu = shell+contrat, rejete = compilateur de fusion. Apres #137.',
    updatedAt: D(6, 21),
  },
  {
    id: 139,
    title: 'Mode "Gros Projet" — build incremental d\'un produit unique',
    status: 'idea',
    model: 'opus',
    effort: 'XL',
    tags: ['concept', 'composer-os', 'kanban'],
    deps: [137],
    notes: 'Socle-d\'abord puis increments bornes : Perfect Plan -> squelette (design system + router + layout + donnees) -> page/stage par page, Kanban de pages. Un site 20 pages, un jeu a stages.',
    updatedAt: D(6, 21),
  },
  {
    id: 140,
    title: 'Renforcement des 4 points fragiles d\'architecture (dette)',
    status: 'idea',
    model: 'opus',
    effort: 'L',
    tags: ['dette', 'architecture'],
    deps: [139],
    notes: 'App.jsx god-component · nav stringly-typed · regex flux · couverture de test inegale. #1+#2 = router-fichier+TS de #139 · #3 -> tree-sitter · #4 -> Vitest+RTL.',
    updatedAt: D(6, 21),
  },
  {
    id: 141,
    title: 'Vault de projet auto-cartographie (inspiration Obsidian)',
    status: 'idea',
    model: 'opus',
    effort: 'L',
    tags: ['concept', 'vault', 'documentation'],
    deps: [139],
    notes: 'Un vault docs/ par gros projet (MOC + pages-entites + Mermaid), maintenu par un agent Cartographe + passe nocturne anti-derive. MangoOS le fait deja pour lui-meme (le wiki/).',
    updatedAt: D(6, 21),
  },
  {
    id: 135,
    title: 'Cerveaux heterogenes par agent — orchestrateur + experts legers',
    status: 'idea',
    model: 'opus',
    effort: 'L',
    tags: ['concept', 'kernel', 'brain'],
    deps: [108],
    notes: 'Idee fondatrice : au lieu d\'un gros cerveau generaliste, un petit raisonneur orchestre des experts specialises legers. A evaluer/prototyper.',
    updatedAt: D(6, 20),
  },
  {
    id: 107,
    title: 'Import design system -> contrat dur (patrouilleur coherence DS)',
    status: 'idea',
    model: 'sonnet',
    effort: 'M',
    tags: ['design', 'patrouilleur'],
    deps: [73],
    notes: 'Source LOCALE (export tokens Figma JSON / CSS vars colles) -> .design-system.md, puis patrouilleur "coherence DS" qui signale couleurs/typo/spacing hors contrat. Pas de Figma MCP live.',
    updatedAt: D(6, 19),
  },
  {
    id: 53,
    title: 'Carte des capacites — synthese vivante de toutes les competences',
    status: 'idea',
    model: 'opus',
    effort: 'L',
    tags: ['meta', 'audit'],
    deps: [],
    notes: 'Vue d\'ensemble de tous les blocs prompt, outils MCP, skills, super-agents, modes, avec leur POIDS (tokens/latence) pour arbitrer par phase/mode. Apres audit #13.',
    updatedAt: D(6, 14),
  },
  {
    id: 55,
    title: 'Fine-tuning LoRA de l\'Eleve — auto-amelioration du modele',
    status: 'idea',
    model: 'opus',
    effort: 'XL',
    tags: ['ml', 'eleve-local', 'exploratoire'],
    deps: [32],
    notes: 'Dataset depuis les runs nocturnes valides -> adaptateur LoRA local sur l\'Eleve (Gemma 4) -> il code reellement mieux nuit apres nuit. Vrai palier "poids qui evoluent". Voir #55a (collecte).',
    updatedAt: D(6, 17),
  },
  {
    id: 65,
    title: 'Vision · Apercu headless en generation nocturne',
    status: 'idea',
    model: 'sonnet',
    effort: 'M',
    tags: ['vision', 'nocturne'],
    deps: [],
    notes: 'La nuit, pas de serveur d\'apercu -> l\'agent code a l\'aveugle. Lancer un preview headless pendant buildOne + brancher setVisionContext sur l\'URL reelle. Debloque la boucle patch->snapshot la nuit.',
    updatedAt: D(6, 14),
  },
  {
    id: 66,
    title: 'Vision · Juge #59 sur capture du rendu (pas le code)',
    status: 'idea',
    model: 'sonnet',
    effort: 'M',
    tags: ['vision', 'nocturne', 'juge'],
    deps: [65],
    notes: 'Aujourd\'hui judgeProject note le CODE source -> "design=8" juge le code, pas le visuel. Capturer un snapshot du rendu et le passer au juge en entree vision. Rend la note design honnete.',
    updatedAt: D(6, 14),
  },
  {
    id: 67,
    title: 'Vision · Diff visuel objectif vs cible (pixelmatch/SSIM)',
    status: 'idea',
    model: 'opus',
    effort: 'L',
    tags: ['vision', 'mesure'],
    deps: [65],
    notes: 'La critique visuelle reste auto-declarative. Comparer la capture a la cible via une vraie metrique pour remplacer "je crois que c\'est bon" par une mesure. Decision d\'archi (choix de metrique).',
    updatedAt: D(6, 14),
  },
  {
    id: 90,
    title: 'Rationalisation explicite des escalades (STaR adapte)',
    status: 'idea',
    model: 'sonnet',
    effort: 'S',
    tags: ['eleve-local', 'axiomes'],
    deps: [],
    notes: 'Enrichir le prompt d\'escalade pour que Claude redige le raisonnement pas-a-pas -> l\'axiome devient un RAISONNEMENT, pas juste une regle. 1 modif dans eleve.ts. Aligne "bases d\'abord".',
    updatedAt: D(6, 14),
  },
  {
    id: 77,
    title: 'Veille thematique sur sites cibles (Awwwards, Dribbble...)',
    status: 'idea',
    model: 'sonnet',
    effort: 'M',
    tags: ['veille', 'design'],
    deps: [],
    notes: 'Pipeline de decouverte autonome ciblee par domaine : Mango decide quels sites sont pertinents pour le projet actif et y cherche des patterns. Connecte a #50 (banque de refs) et #46 (Sharingan).',
    updatedAt: D(6, 14),
  },
  {
    id: 13,
    title: 'Audit & optimisation des couts (fin de Fable)',
    status: 'idea',
    model: 'opus',
    effort: 'M',
    tags: ['audit', 'metriques'],
    deps: [],
    notes: 'Programme 2026-06-22 : cartographier les couts et faiblesses depuis .metrics.jsonl. Debloque #53, #65-67, #84-92 (plusieurs idees attendent cet audit).',
    updatedAt: D(6, 14),
  },

  // --- En cours ---
  {
    id: 106,
    title: 'Boucle d\'apprentissage par reverse-engineering — Gemma apprend de Claude',
    status: 'doing',
    model: 'opus',
    effort: 'L',
    tags: ['eleve-local', 'fondatrice'],
    deps: [75, 59, 90],
    notes: 'Phases 1-3 livrees (run-learn.ts + run-finish.ts). (1) juge dans la boucle, (2) diff Gemma/Claude -> procedure+axiome, (3) donner a Gemma les moyens text-injectables (constellations/procedures/DS).',
    updatedAt: D(6, 19),
  },

  // --- Bloque ---
  {
    id: 142,
    title: 'Image Creator — generation d\'images',
    status: 'blocked',
    model: 'sonnet',
    effort: 'M',
    tags: ['creator', 'bloque'],
    deps: [],
    notes: 'Attend REPLICATE_API_TOKEN. Phase Image Creator non operationnelle tant que la cle n\'est pas posee.',
    updatedAt: D(6, 21),
  },
  {
    id: 143,
    title: 'Music Creator — generation audio',
    status: 'blocked',
    model: 'sonnet',
    effort: 'M',
    tags: ['creator', 'bloque'],
    deps: [],
    notes: 'Attend REPLICATE_API_TOKEN. Phase Music Creator non operationnelle tant que la cle n\'est pas posee.',
    updatedAt: D(6, 21),
  },

  // --- Vitrines a faire (#94-#98) ---
  {
    id: 94,
    title: '[VITRINE] Studio d\'architecture interieure premium',
    status: 'idea',
    model: 'sonnet',
    effort: 'L',
    tags: ['vitrine', 'showcase'],
    deps: [],
    notes: '5 pages React Router, hero plein-ecran, galerie filtree + lightbox custom, formulaire valide, nav sticky blur, animations scroll. Refs Sharingan : Zaha Hadid + Snohetta. Template vitrine.',
    updatedAt: D(6, 18),
  },
  {
    id: 95,
    title: '[DASHBOARD] Analytics SaaS type Vercel/Linear',
    status: 'idea',
    model: 'sonnet',
    effort: 'L',
    tags: ['dashboard', 'showcase'],
    deps: [],
    notes: 'Dark mode + toggle, sidebar collapsible, KPI animes, graphique 30j + barres (recharts), table paginee tri/recherche. Archi Elite : composants <200l, hooks separes. 150+ tests. Template shadcn.',
    updatedAt: D(6, 18),
  },
  {
    id: 96,
    title: '[LANDING] Page SaaS "prete a lancer"',
    status: 'idea',
    model: 'sonnet',
    effort: 'M',
    tags: ['landing', 'showcase'],
    deps: [],
    notes: 'Hero + mockup CSS, 6 features, social proof, pricing 3 tiers toggle mensuel/annuel, FAQ accordion, CTA + email valide. WCAG AA, focus visible, clavier. Template daisy.',
    updatedAt: D(6, 18),
  },
  {
    id: 98,
    title: '[JEU] RPG top-down retro (style Zelda)',
    status: 'idea',
    model: 'opus',
    effort: 'XL',
    tags: ['jeu', 'showcase'],
    deps: [],
    notes: 'Carte tuilee en code, perso 4 directions + sprites, 2 ennemis (patrouille/poursuite), combat tour par tour, inventaire, HUD, 2 zones + boss. Archi src/game/. Tests Vitest. Template phaser.',
    updatedAt: D(6, 18),
  },

  // --- Fait (chantiers livres — donnent du poids au board et satisfont les deps) ---
  {
    id: 97,
    title: '[FULLSTACK] MangoCartes — flashcards Anki-like (Supabase)',
    status: 'done',
    model: 'opus',
    effort: 'XL',
    tags: ['fullstack', 'showcase'],
    deps: [],
    notes: 'Genere via MangoOS (pilotage /api/chat). MVP $0.94 -> Elite $1.79, 11/11 tests Vitest. Auth+RLS Supabase, repetition espacee pure testee, stats recharts. Palette mangopulse reutilisee (reuse 50%).',
    updatedAt: D(6, 20),
  },
  {
    id: 108,
    title: 'Kernel MangoOS — infrastructure 5 piliers',
    status: 'done',
    model: 'opus',
    effort: 'L',
    tags: ['kernel', 'infra'],
    deps: [],
    notes: 'Brain Adapter · Event Bus · Blackboard · MCP/Registre d\'outils · Tracing OpenTelemetry. 173 tests verts. Le socle sur lequel s\'arment MangoQA, la curation, les traces.',
    updatedAt: D(6, 19),
  },
  {
    id: 115,
    title: 'Persistance SQLite-vec du Blackboard',
    status: 'done',
    model: 'opus',
    effort: 'M',
    tags: ['kernel', 'blackboard'],
    deps: [108],
    notes: 'Le store d\'artefacts passe de la memoire a un backend persistant via node:sqlite (Node 25, zero install native). Survie au redemarrage prouvee. sqlite-vec branchable plus tard sans changer l\'interface.',
    updatedAt: D(6, 20),
  },
  {
    id: 117,
    title: 'Vrais artefacts dans le Blackboard — bibliotheque cross-projet',
    status: 'done',
    model: 'sonnet',
    effort: 'M',
    tags: ['blackboard', 'curation'],
    deps: [115],
    notes: 'Observateur design.reference/design.produced depose chaque palette dans le Blackboard (cross-projet, dedup par hash). paletteEmbedding = histogramme RGB 27 dims. Recherche "designs aux couleurs proches".',
    updatedAt: D(6, 20),
  },
  {
    id: 121,
    title: 'Mesure de la reutilisation effective des artefacts',
    status: 'done',
    model: 'sonnet',
    effort: 'M',
    tags: ['curation', 'metriques'],
    deps: [117],
    notes: 'Ferme la boucle de preuve : un Read sur .components/.skills/.procedures = reutilisation. ReuseCollector abonne au Bus -> taux + par type + top artefacts. L\'agent utilise-t-il vraiment ce qu\'on reinjecte ?',
    updatedAt: D(6, 20),
  },
  {
    id: 123,
    title: 'Correlation reutilisation <-> cout/qualite — la memoire RAPPORTE ?',
    status: 'done',
    model: 'sonnet',
    effort: 'M',
    tags: ['curation', 'metriques'],
    deps: [121],
    notes: 'Apparie artifact.reuse + chat.turn dans le meme tour : un tour qui reutilise coute-t-il moins, va-t-il plus vite, reussit-il mieux ? Deltas cout/vitesse/succes + garde-fou echantillon mince.',
    updatedAt: D(6, 20),
  },
  {
    id: 125,
    title: 'Curation nocturne ponderee par le rendement',
    status: 'done',
    model: 'opus',
    effort: 'M',
    tags: ['curation', 'nocturne'],
    deps: [123],
    notes: 'La recolte nocturne enrichit en priorite la bibliotheque au meilleur rendement mesure (bandit honnete : exploit/explore/deprioritize). Mesurer -> reinjecter -> prouver -> chiffrer -> ORIENTER : boucle bouclee.',
    updatedAt: D(6, 20),
  },
  {
    id: 130,
    title: 'Amortissement du reglage des knobs (filtre EMA)',
    status: 'done',
    model: 'sonnet',
    effort: 'S',
    tags: ['curation', 'controle'],
    deps: [125],
    notes: 'Les poids appliques ne bougent que d\'une fraction alpha vers la cible -> un variateur avec inertie : suit la preuve sans broncher au bruit. La boucle de controle cesse d\'osciller.',
    updatedAt: D(6, 20),
  },
  {
    id: 110,
    title: 'MangoQA Visage 1 — Le Disjoncteur',
    status: 'done',
    model: 'opus',
    effort: 'M',
    tags: ['mangoqa', 'gardien'],
    deps: [108],
    notes: 'Gardien deterministe, zero LLM, defensif, borne : peut ARRETER, jamais creer ni modifier. 5 reflexes (circuit nocturne, garde-fou cout, verrou regression, derive memoire, kill switch agent). 38/38 tests.',
    updatedAt: D(6, 19),
  },
  {
    id: 111,
    title: 'MangoQA Visage 3 — L\'Oeil Design',
    status: 'done',
    model: 'opus',
    effort: 'M',
    tags: ['mangoqa', 'design'],
    deps: [108],
    notes: 'Couche objective : rigide sur le mesurable (WCAG 2.1 exact, adherence palette/echelle, derive vs Sharingan), souple sur le subjectif (questions de convergence), JAMAIS bloquant. 60/60 tests.',
    updatedAt: D(6, 19),
  },
  {
    id: 137,
    title: 'Auditeur de Flux — 4e visage MangoQA (coherence de nav)',
    status: 'done',
    model: 'opus',
    effort: 'L',
    tags: ['mangoqa', 'flux'],
    deps: [108],
    notes: 'Tier 0 (deterministe : graphe de nav + contrat de flux -> routes mortes) + Tier 1 (LLM conseil cost-aware : R4 + coherence semantique). Conseil/jamais bloquant. Valide sur le cockpit.',
    updatedAt: D(6, 21),
  },
  {
    id: 136,
    title: 'Bureau OS — interface iconique + fenetres superposables',
    status: 'done',
    model: 'opus',
    effort: 'L',
    tags: ['bureau-os', 'ui'],
    deps: [],
    notes: 'Refonte navigation COMPLETE P0->P4 : dock epure + Launcher, toute app = une fenetre du WindowManager, rail workspace facon VS Code, ecran Reglages unique. Palette systeme iOS/Apple.',
    updatedAt: D(6, 21),
  },
  {
    id: 99,
    title: 'Perfect Plan — questionnaire guide + dossier references',
    status: 'done',
    model: 'sonnet',
    effort: 'L',
    tags: ['cadrage', 'plan'],
    deps: [],
    notes: 'Avant le 1er prompt : (1) questionnaire 5 questions (type/style/nav/donnees/ambiance), (2) dossier refs (URLs Sharingan + palette + notes). Contrat contraignant injecte dans le system prompt.',
    updatedAt: D(6, 18),
  },
  {
    id: 105,
    title: 'MangoQA — framework d\'audit autonome (Production Aveugle / Audit Fantome)',
    status: 'done',
    model: 'opus',
    effort: 'XL',
    tags: ['mangoqa', 'infra'],
    deps: [],
    notes: 'Repo separe, process Node independant. 6 branches d\'audit en parallele + detection par sentinelle. Cycle complet valide (build -> Feu Rouge -> correction -> Feu Vert).',
    updatedAt: D(6, 19),
  },
  {
    id: 73,
    title: 'L\'armee automatique — patrouilleurs specialises auto-convoques',
    status: 'done',
    model: 'opus',
    effort: 'L',
    tags: ['agents', 'audit'],
    deps: [],
    notes: '5 patrouilleurs convoques par detection de contexte : Accessibilite · Securite · SEO · Performance · Bundle. Module patrol.ts, reveille fire-and-forget apres chaque tour. 33/33 tests.',
    updatedAt: D(6, 16),
  },
  {
    id: 75,
    title: 'Memoire procedurale — magasin .procedures/',
    status: 'done',
    model: 'sonnet',
    effort: 'L',
    tags: ['memoire', 'apprentissage'],
    deps: [],
    notes: 'Schemas de resolution (situation -> raisonnement -> pieges -> etapes validees) recuperes par similarite semantique (embeddings Ollama + cosinus, seuil 0.65). Skill=code · axiome=regle · procedure=demarche.',
    updatedAt: D(6, 16),
  },
  {
    id: 32,
    title: 'Boucle d\'entrainement nocturne',
    status: 'done',
    model: 'sonnet',
    effort: 'M',
    tags: ['nocturne', 'apprentissage'],
    deps: [],
    notes: 'CLI autonome : genere en boucle des creations diverses pendant que Raf dort (Eleve local $0, escalade Claude plafonnee). Remplit la courbe d\'apprentissage + genere des axiomes. 3600 combos.',
    updatedAt: D(6, 14),
  },
]
