import type { Idea } from './types'

// Seed extrait de statut.md (tableau consolide des idees, 2026-06-21).
// Donnees REELLES — chaque carte est une idee/chantier MangoOS, raccourcie au concept.
// Raf completera le reste : c'est le but de l'outil.

// Dates plausibles deterministes (UTC) pour eviter un seed "tout au meme instant".
const D = (m: number, d: number) => Date.UTC(2026, m - 1, d, 9, 0, 0)

export const SEED: Idea[] = [
  // --- Concepts & chantiers strategiques recents (le coeur de la decision) ---
  {
    id: 138,
    title: 'OS d\'apps personnelles — composer les apps en suite type Office',
    status: 'idea',
    model: 'opus',
    effort: 'XL',
    tags: ['concept', 'composer-os', 'architecture'],
    deps: [137],
    notes: 'Shell + contrat "MangoApp" qui heberge des apps autonomes (3 couches : design / donnee partagee / nav). Retenu = shell+contrat, rejete = compilateur de fusion. Apres #137.',
    updatedAt: D(6, 21),
  },
  {
    id: 139,
    title: 'Mode "Gros Projet" — build incremental d\'un produit unique',
    status: 'idea',
    model: 'opus',
    effort: 'XL',
    tags: ['concept', 'composer-os', 'kanban'],
    deps: [137],
    notes: 'Socle-d\'abord puis increments bornes : Perfect Plan -> squelette (design system + router + layout + donnees) -> page/stage par page, Kanban de pages. Un site 20 pages, un jeu a stages.',
    updatedAt: D(6, 21),
  },
  {
    id: 140,
    title: 'Renforcement des 4 points fragiles d\'architecture (dette)',
    status: 'idea',
    model: 'opus',
    effort: 'L',
    tags: ['dette', 'architecture'],
    deps: [139],
    notes: 'App.jsx god-component · nav stringly-typed · regex flux · couverture de test inegale. #1+#2 = router-fichier+TS de #139 · #3 -> tree-sitter · #4 -> Vitest+RTL.',
    updatedAt: D(6, 21),
  },
  {
    id: 141,
    title: 'Vault de projet auto-cartographie (inspiration Obsidian)',
    status: 'idea',
    model: 'opus',
    effort: 'L',
    tags: ['concept', 'vault', 'documentation'],
    deps: [139],
    notes: 'Un vault docs/ par gros projet (MOC + pages-entites + Mermaid), maintenu par un agent Cartographe + passe nocturne anti-derive. MangoOS le fait deja pour lui-meme (le wiki/).',
    updatedAt: D(6, 21),
  },
  {
    id: 135,
    title: 'Cerveaux heterogenes par agent — orchestrateur + experts legers',
    status: 'idea',
    model: 'opus',
    effort: 'L',
    tags: ['concept', 'kernel', 'brain'],
    deps: [108],
    notes: 'Idee fondatrice : au lieu d\'un gros cerveau generaliste, un petit raisonneur orchestre des experts specialises legers. A evaluer/prototyper.',
    updatedAt: D(6, 20),
  },
  {
    id: 107,
    title: 'Import design system -> contrat dur (patrouilleur coherence DS)',
    status: 'idea',
    model: 'sonnet',
    effort: 'M',
    tags: ['design', 'patrouilleur'],
    deps: [73],
    notes: 'Source LOCALE (export tokens Figma JSON / CSS vars colles) -> .design-system.md, puis patrouilleur "coherence DS" qui signale couleurs/typo/spacing hors contrat. Pas de Figma MCP live.',
    updatedAt: D(6, 19),
  },
  {
    id: 53,
    title: 'Carte des capacites — synthese vivante de toutes les competences',
    status: 'idea',
    model: 'opus',
    effort: 'L',
    tags: ['meta', 'audit'],
    deps: [],
    notes: 'Vue d\'ensemble de tous les blocs prompt, outils MCP, skills, super-agents, modes, avec leur POIDS (tokens/latence) pour arbitrer par phase/mode. Apres audit #13.',
    updatedAt: D(6, 14),
  },
  {
    id: 55,
    title: 'Fine-tuning LoRA de l\'Eleve — auto-amelioration du modele',
    status: 'idea',
    model: 'opus',
    effort: 'XL',
    tags: ['ml', 'eleve-local', 'exploratoire'],
    deps: [32],
    notes: 'Dataset depuis les runs nocturnes valides -> adaptateur LoRA local sur l\'Eleve (Gemma 4) -> il code reellement mieux nuit apres nuit. Vrai palier "poids qui evoluent". Voir #55a (collecte).',
    updatedAt: D(6, 17),
  },
  {
    id: 65,
    title: 'Vision · Apercu headless en generation nocturne',
    status: 'done',
    model: 'sonnet',
    effort: 'M',
    tags: ['vision', 'nocturne'],
    deps: [],
    notes: 'RESOLU : le systeme de vision (vois_ecran #151) capture le rendu via Playwright headless. L\'agent peut voir l\'apercu meme sans serveur visible. La boucle patch->snapshot fonctionne en generation nocturne.',
    updatedAt: D(6, 22),
  },
  {
    id: 66,
    title: 'Vision · Juge #59 sur capture du rendu (pas le code)',
    status: 'done',
    model: 'sonnet',
    effort: 'M',
    tags: ['vision', 'nocturne', 'juge'],
    deps: [65],
    notes: 'RESOLU : le design-coach (#152) et le juge de vision evaluent desormais la CAPTURE du rendu, pas le code source. La note design est honnete. Reste L1 : variance de notation du VL (moyennage N passes en cours).',
    updatedAt: D(6, 22),
  },
  {
    id: 67,
    title: 'Vision · Diff visuel objectif vs cible (pixelmatch/SSIM)',
    status: 'idea',
    model: 'opus',
    effort: 'L',
    tags: ['vision', 'mesure'],
    deps: [65],
    notes: 'La critique visuelle reste auto-declarative. Comparer la capture a la cible via une vraie metrique pour remplacer "je crois que c\'est bon" par une mesure. Decision d\'archi (choix de metrique).',
    updatedAt: D(6, 14),
  },
  {
    id: 90,
    title: 'Rationalisation explicite des escalades (STaR adapte)',
    status: 'idea',
    model: 'sonnet',
    effort: 'S',
    tags: ['eleve-local', 'axiomes'],
    deps: [],
    notes: 'Enrichir le prompt d\'escalade pour que Claude redige le raisonnement pas-a-pas -> l\'axiome devient un RAISONNEMENT, pas juste une regle. 1 modif dans eleve.ts. Aligne "bases d\'abord".',
    updatedAt: D(6, 14),
  },
  {
    id: 77,
    title: 'Veille thematique sur sites cibles (Awwwards, Dribbble...)',
    status: 'idea',
    model: 'sonnet',
    effort: 'M',
    tags: ['veille', 'design'],
    deps: [],
    notes: 'Pipeline de decouverte autonome ciblee par domaine : Mango decide quels sites sont pertinents pour le projet actif et y cherche des patterns. Connecte a #50 (banque de refs) et #46 (Sharingan).',
    updatedAt: D(6, 14),
  },
  {
    id: 13,
    title: 'Audit & optimisation des couts (fin de Fable)',
    status: 'done',
    model: 'opus',
    effort: 'M',
    tags: ['audit', 'metriques'],
    deps: [],
    notes: 'LIVRE : audit-general-2026-06.md produit. Cartographie complete des couts et faiblesses depuis .metrics.jsonl. A debloque #53, #65-67, #84-92. Reste L7 : cout GLM cloud non trace (en-tetes usage a capter).',
    updatedAt: D(6, 23),
  },
  {
    id: 147,
    title: 'PDF-Vision : Mango VOIT les PDF (rendu page->PNG + zoom/crop)',
    status: 'done',
    model: 'opus',
    effort: 'L',
    tags: ['vision', 'pdf', 'document'],
    deps: [108],
    notes: 'Outil lire_document (#157) : pdfjs rend les pages en PNG -> le VL les lit. Zoom/crop + images embarquees. Debloque la lecture de PDF scannes (L4 : repli vois_ecran sur page rendue).',
    updatedAt: D(6, 22),
  },
  {
    id: 149,
    title: 'Design-Coach : calibrer le juge design sur les choix reels',
    status: 'doing',
    model: 'sonnet',
    effort: 'M',
    tags: ['design', 'juge', 'calibrage'],
    deps: [66],
    notes: 'Le design-coach (#152) guide l\'agent vers de meilleures decisions visuelles. Calibrage sur les choix reels de Raf en cours. Reste L1 : variance de notation du VL (moyennage N passes).',
    updatedAt: D(6, 24),
  },
  {
    id: 151,
    title: 'vois_ecran — vision du rendu en boucle fermee',
    status: 'done',
    model: 'sonnet',
    effort: 'M',
    tags: ['vision', 'tool'],
    deps: [65],
    notes: 'Outil Eleve : capture le rendu (Playwright headless) -> le VL analyse le visuel reel. Ferme la boucle code->capture->critique->corrige. L\'agent ne code plus a l\'aveugle.',
    updatedAt: D(6, 22),
  },
  {
    id: 152,
    title: 'Oeil-Coach : juge design sur capture (pas le code)',
    status: 'done',
    model: 'sonnet',
    effort: 'M',
    tags: ['design', 'vision', 'juge'],
    deps: [151],
    notes: 'Design-coach-routes + design-coach.ts : evalue la CAPTURE du rendu via lentilles design (layout, couleur, typo, espacement). Retourne un score + corrections actionnables. L1 reste : variance VL.',
    updatedAt: D(6, 24),
  },
  {
    id: 153,
    title: 'chercher_image — vraies photos Pexels dans les apps',
    status: 'done',
    model: 'sonnet',
    effort: 'S',
    tags: ['image', 'tool', 'pexels'],
    deps: [],
    notes: 'Outil Eleve : cherche des photos stock reelles via Pexels API et les integre dans le projet genere. Reste L15 : requetes en FR -> pertinence variable (Pexels indexe en EN).',
    updatedAt: D(6, 24),
  },
  {
    id: 154,
    title: 'chercher_web — recherche web keyless best-effort',
    status: 'done',
    model: 'haiku',
    effort: 'S',
    tags: ['web', 'tool', 'search'],
    deps: [],
    notes: 'Outil Eleve : recherche web sans cle (DuckDuckGo/Mojeek). Reste L2 : captcha sous charge sans cle. Tavily (deja cable) pour le robuste.',
    updatedAt: D(6, 24),
  },
  {
    id: 156,
    title: 'chercher_artefact — reutiliser composants/layouts/skills/procedures',
    status: 'done',
    model: 'opus',
    effort: 'L',
    tags: ['curation', 'blackboard', 'reuse'],
    deps: [117],
    notes: 'L3 RESOLU : une seule requete remonte 5 types (composants+layouts+skills+procedures+palettes). Layouts = type distinct (layouts.ts). Skills et procedures exposes dans l\'outil. Palettes par texte (adjectifs deterministes).',
    updatedAt: D(6, 26),
  },
  {
    id: 157,
    title: 'lire_document — PDF, Office, images en entree',
    status: 'done',
    model: 'sonnet',
    effort: 'M',
    tags: ['document', 'tool', 'pdf'],
    deps: [147],
    notes: 'Outil Eleve : extrait texte de PDF (pdfjs), OOXML (mammoth/officeparser), images (VL). Restes : L4 (PDF scanne = image pure -> vois_ecran), L5 (.doc/.xls binaire legacy), L6 (.xlsx tabulaire fin).',
    updatedAt: D(6, 24),
  },
  {
    id: 158,
    title: 'extraire_site — crawler un site de reference -> dossier de design',
    status: 'done',
    model: 'opus',
    effort: 'XL',
    tags: ['web', 'sharingan', 'design', 'tool'],
    deps: [154, 153],
    notes: 'Pipeline complet : crawl (scrapeExternal) -> analyse design (sharinganAnalyze) -> vision (captureExternal) -> dossier site-text. Genere des requetes image Pexels. Restes : L11 (selection de liens), L12 (dedup www.), L13 (seed charge 3x), L14 (vision multi-pages), L15 (requetes FR).',
    updatedAt: D(6, 26),
  },
  {
    id: 159,
    title: 'planifier — Perfect Plan ancre dans le prompt de generation',
    status: 'done',
    model: 'opus',
    effort: 'L',
    tags: ['plan', 'tool', 'contexte'],
    deps: [],
    notes: 'Outil Eleve : genere un .perfect-plan.md structure (contexte, design, pages, data). L17 RESOLU : rappel du plan en cours de boucle (pas seulement aux relances) via planReminder. L18 RESOLU : etape_faite(n) coche la progression.',
    updatedAt: D(6, 28),
  },
  {
    id: 160,
    title: 'Contexte d\'abord : chercher l\'identite reelle avant de coder',
    status: 'done',
    model: 'opus',
    effort: 'M',
    tags: ['contexte', 'fondatrice', 'web'],
    deps: [154, 158],
    notes: 'PRINCIPE DE BASE (Raf, 2026-06-27) : avant de coder, chercher l\'identite/contexte reel du sujet sur Internet. Outils dans l\'ordre : planifier -> sharingan/extraire_site -> chercher_web -> chercher_image -> synthese .perfect-plan.md. Ancre dans le prompt de generation.',
    updatedAt: D(6, 27),
  },
  {
    id: 162,
    title: 'Atelier de cerveaux — forge d\'agents specialises',
    status: 'done',
    model: 'opus',
    effort: 'L',
    tags: ['kernel', 'brain', 'forge'],
    deps: [108, 135],
    notes: 'Atelier integre : forge des cerveaux dedies par agent (fini "gemma tout seul x10"). Forgeron = Opus. Brain-registry + brain-dispatch pour router les taches vers le bon cerveau.',
    updatedAt: D(6, 24),
  },
  {
    id: 164,
    title: 'Le Stratège — escalade et arbitrage des cerveaux',
    status: 'done',
    model: 'opus',
    effort: 'L',
    tags: ['kernel', 'stratege', 'brain'],
    deps: [162],
    notes: 'Phase 4/4 complete : echelle d\'escalade de l\'executant (brain-inadequate) + metrique de competence + cerveau pour les cas ambigus + echelle d\'escalade bornee. Le Stratège decide quel cerveau traite quelle tache.',
    updatedAt: D(6, 27),
  },
  {
    id: 166,
    title: 'La main Internet — l\'Eleve peut appeler une API (GET/POST)',
    status: 'done',
    model: 'sonnet',
    effort: 'M',
    tags: ['eleve-local', 'http', 'tool'],
    deps: [],
    notes: 'Outil Eleve : appelle des APIs externes (GET/POST), borde + anti-SSRF. L\'agent peut consommer de vraies donnees (weather, crypto, etc.) dans ses apps generees.',
    updatedAt: D(6, 27),
  },
  {
    id: 168,
    title: 'Boucle d\'auto-evolution — Mango note ses lacunes en live',
    status: 'doing',
    model: 'opus',
    effort: 'XL',
    tags: ['self-evolution', 'forge', 'meta'],
    deps: [162],
    notes: 'Tranche 1 (SEMI-AUTO) livree : Mango detecte ses lacunes en live -> le forgeron cree l\'agent cible. Tranche 2 : forge AUTO sous disjoncteur + UI « Lacunes a combler ». 2 bugs debusques et corriges en live. Vers le FULL-AUTO.',
    updatedAt: D(6, 29),
  },
  {
    id: 172,
    title: 'Hooks Mango — cycle de vie des runs (pre/post/on-error)',
    status: 'done',
    model: 'sonnet',
    effort: 'M',
    tags: ['hooks', 'infra'],
    deps: [108],
    notes: 'mango-hooks.ts + mango-hooks-config.ts : hooks declaratifs pre-run, post-run, on-error. Config injectable. 33+17 tests verts. Permet d\'injecter de la logique sans toucher au coeur.',
    updatedAt: D(6, 28),
  },
  {
    id: 173,
    title: 'Loop — boucle de generation nocturne autonome',
    status: 'done',
    model: 'opus',
    effort: 'L',
    tags: ['nocturne', 'loop', 'auto'],
    deps: [65, 172],
    notes: 'Boucle nocturne : Mango genere, evalue, corrige des projets en autonomie. Vision headless + hooks + plan ancre. Les runs nocturnes valident les axiomes et remplissent les magasins de connaissances.',
    updatedAt: D(6, 28),
  },
  {
    id: 174,
    title: 'Skills — savoir-faire reutilisable divulgue progressivement',
    status: 'done',
    model: 'sonnet',
    effort: 'M',
    tags: ['skills', 'curation', 'tool'],
    deps: [117],
    notes: 'skills.ts : SKILL.md par classe de savoir-faire. Divulgation progressive : seules les metadonnees au prompt, lecture a la demande. Expose dans chercher_artefact (#156). Reutilise cross-projet.',
    updatedAt: D(6, 28),
  },
  {
    id: 175,
    title: 'Subagents — delegation a des agents specialises',
    status: 'done',
    model: 'opus',
    effort: 'L',
    tags: ['subagents', 'kernel', 'delegation'],
    deps: [108],
    notes: 'Delegation a des sous-agents (builder, qa, etc.) via options.agents du SDK. Outils fichiers seulement pour builder (pas de Bash -> pas de conflit npm/preview). Reserve aux gros chantiers a volets independants.',
    updatedAt: D(6, 28),
  },

  // --- En cours ---
  {
    id: 106,
    title: 'Boucle d\'apprentissage par reverse-engineering — Gemma apprend de Claude',
    status: 'done',
    model: 'opus',
    effort: 'L',
    tags: ['eleve-local', 'fondatrice'],
    deps: [75, 59, 90],
    notes: 'Phases 1-3 livrees (run-learn.ts + run-finish.ts). (1) juge dans la boucle, (2) diff Gemma/Claude -> procedure+axiome, (3) donner a Gemma les moyens text-injectables (constellations/procedures/DS). Puis etendu : auto-amelioration barreaux 1-4 (copie isolee, GLM s\'auto-verifie tsc, execute ses tests en bac a sable, ameliore son propre code). Boucle d\'auto-evolution #168 industrialisee.',
    updatedAt: D(6, 29),
  },

  // --- Bloque ---
  {
    id: 142,
    title: 'Image Creator — generation d\'images',
    status: 'done',
    model: 'sonnet',
    effort: 'M',
    tags: ['creator', 'flux-local'],
    deps: [],
    notes: 'RESOLU EN LOCAL SOUVERAIN ($0) : outil genere_image(prompt) via API ComfyUI locale -> Flux schnell GGUF -> PNG dans public/generated/. Prouve live sur GTX 1080 Ti (~4 min/image). Repli chercher_image/Pexels si ComfyUI down. Pas besoin de Replicate.',
    updatedAt: D(6, 29),
  },
  {
    id: 143,
    title: 'Music Creator — generation audio',
    status: 'blocked',
    model: 'sonnet',
    effort: 'M',
    tags: ['creator', 'bloque'],
    deps: [],
    notes: 'Attend un backend de generation audio local (style AudioCraft/MusicGen via Ollama ou ComfyUI audio). Pas de solution locale souveraine equivalente a Flux pour les images pour l\'instant.',
    updatedAt: D(6, 29),
  },

  // --- Vitrines a faire (#94-#98) ---
  {
    id: 94,
    title: '[VITRINE] Studio d\'architecture interieure premium',
    status: 'idea',
    model: 'sonnet',
    effort: 'L',
    tags: ['vitrine', 'showcase'],
    deps: [],
    notes: '5 pages React Router, hero plein-ecran, galerie filtree + lightbox custom, formulaire valide, nav sticky blur, animations scroll. Refs Sharingan : Zaha Hadid + Snohetta. Template vitrine.',
    updatedAt: D(6, 18),
  },
  {
    id: 95,
    title: '[DASHBOARD] Analytics SaaS type Vercel/Linear',
    status: 'idea',
    model: 'sonnet',
    effort: 'L',
    tags: ['dashboard', 'showcase'],
    deps: [],
    notes: 'Dark mode + toggle, sidebar collapsible, KPI animes, graphique 30j + barres (recharts), table paginee tri/recherche. Archi Elite : composants <200l, hooks separes. 150+ tests. Template shadcn.',
    updatedAt: D(6, 18),
  },
  {
    id: 96,
    title: '[LANDING] Page SaaS "prete a lancer"',
    status: 'idea',
    model: 'sonnet',
    effort: 'M',
    tags: ['landing', 'showcase'],
    deps: [],
    notes: 'Hero + mockup CSS, 6 features, social proof, pricing 3 tiers toggle mensuel/annuel, FAQ accordion, CTA + email valide. WCAG AA, focus visible, clavier. Template daisy.',
    updatedAt: D(6, 18),
  },
  {
    id: 98,
    title: '[JEU] RPG top-down retro (style Zelda)',
    status: 'idea',
    model: 'opus',
    effort: 'XL',
    tags: ['jeu', 'showcase'],
    deps: [],
    notes: 'Carte tuilee en code, perso 4 directions + sprites, 2 ennemis (patrouille/poursuite), combat tour par tour, inventaire, HUD, 2 zones + boss. Archi src/game/. Tests Vitest. Template phaser.',
    updatedAt: D(6, 18),
  },

  // --- Fait (chantiers livres — donnent du poids au board et satisfont les deps) ---
  {
    id: 97,
    title: '[FULLSTACK] MangoCartes — flashcards Anki-like (Supabase)',
    status: 'done',
    model: 'opus',
    effort: 'XL',
    tags: ['fullstack', 'showcase'],
    deps: [],
    notes: 'Genere via MangoOS (pilotage /api/chat). MVP $0.94 -> Elite $1.79, 11/11 tests Vitest. Auth+RLS Supabase, repetition espacee pure testee, stats recharts. Palette mangopulse reutilisee (reuse 50%).',
    updatedAt: D(6, 20),
  },
  {
    id: 108,
    title: 'Kernel MangoOS — infrastructure 5 piliers',
    status: 'done',
    model: 'opus',
    effort: 'L',
    tags: ['kernel', 'infra'],
    deps: [],
    notes: 'Brain Adapter · Event Bus · Blackboard · MCP/Registre d\'outils · Tracing OpenTelemetry. 173 tests verts. Le socle sur lequel s\'arment MangoQA, la curation, les traces.',
    updatedAt: D(6, 19),
  },
  {
    id: 115,
    title: 'Persistance SQLite-vec du Blackboard',
    status: 'done',
    model: 'opus',
    effort: 'M',
    tags: ['kernel', 'blackboard'],
    deps: [108],
    notes: 'Le store d\'artefacts passe de la memoire a un backend persistant via node:sqlite (Node 25, zero install native). Survie au redemarrage prouvee. sqlite-vec branchable plus tard sans changer l\'interface.',
    updatedAt: D(6, 20),
  },
  {
    id: 117,
    title: 'Vrais artefacts dans le Blackboard — bibliotheque cross-projet',
    status: 'done',
    model: 'sonnet',
    effort: 'M',
    tags: ['blackboard', 'curation'],
    deps: [115],
    notes: 'Observateur design.reference/design.produced depose chaque palette dans le Blackboard (cross-projet, dedup par hash). paletteEmbedding = histogramme RGB 27 dims. Recherche "designs aux couleurs proches".',
    updatedAt: D(6, 20),
  },
  {
    id: 121,
    title: 'Mesure de la reutilisation effective des artefacts',
    status: 'done',
    model: 'sonnet',
    effort: 'M',
    tags: ['curation', 'metriques'],
    deps: [117],
    notes: 'Ferme la boucle de preuve : un Read sur .components/.skills/.procedures = reutilisation. ReuseCollector abonne au Bus -> taux + par type + top artefacts. L\'agent utilise-t-il vraiment ce qu\'on reinjecte ?',
    updatedAt: D(6, 20),
  },
  {
    id: 123,
    title: 'Correlation reutilisation <-> cout/qualite — la memoire RAPPORTE ?',
    status: 'done',
    model: 'sonnet',
    effort: 'M',
    tags: ['curation', 'metriques'],
    deps: [121],
    notes: 'Apparie artifact.reuse + chat.turn dans le meme tour : un tour qui reutilise coute-t-il moins, va-t-il plus vite, reussit-il mieux ? Deltas cout/vitesse/succes + garde-fou echantillon mince.',
    updatedAt: D(6, 20),
  },
  {
    id: 125,
    title: 'Curation nocturne ponderee par le rendement',
    status: 'done',
    model: 'opus',
    effort: 'M',
    tags: ['curation', 'nocturne'],
    deps: [123],
    notes: 'La recolte nocturne enrichit en priorite la bibliotheque au meilleur rendement mesure (bandit honnete : exploit/explore/deprioritize). Mesurer -> reinjecter -> prouver -> chiffrer -> ORIENTER : boucle bouclee.',
    updatedAt: D(6, 20),
  },
  {
    id: 130,
    title: 'Amortissement du reglage des knobs (filtre EMA)',
    status: 'done',
    model: 'sonnet',
    effort: 'S',
    tags: ['curation', 'controle'],
    deps: [125],
    notes: 'Les poids appliques ne bougent que d\'une fraction alpha vers la cible -> un variateur avec inertie : suit la preuve sans broncher au bruit. La boucle de controle cesse d\'osciller.',
    updatedAt: D(6, 20),
  },
  {
    id: 110,
    title: 'MangoQA Visage 1 — Le Disjoncteur',
    status: 'done',
    model: 'opus',
    effort: 'M',
    tags: ['mangoqa', 'gardien'],
    deps: [108],
    notes: 'Gardien deterministe, zero LLM, defensif, borne : peut ARRETER, jamais creer ni modifier. 5 reflexes (circuit nocturne, garde-fou cout, verrou regression, derive memoire, kill switch agent). 38/38 tests.',
    updatedAt: D(6, 19),
  },
  {
    id: 111,
    title: 'MangoQA Visage 3 — L\'Oeil Design',
    status: 'done',
    model: 'opus',
    effort: 'M',
    tags: ['mangoqa', 'design'],
    deps: [108],
    notes: 'Couche objective : rigide sur le mesurable (WCAG 2.1 exact, adherence palette/echelle, derive vs Sharingan), souple sur le subjectif (questions de convergence), JAMAIS bloquant. 60/60 tests.',
    updatedAt: D(6, 19),
  },
  {
    id: 137,
    title: 'Auditeur de Flux — 4e visage MangoQA (coherence de nav)',
    status: 'done',
    model: 'opus',
    effort: 'L',
    tags: ['mangoqa', 'flux'],
    deps: [108],
    notes: 'Tier 0 (deterministe : graphe de nav + contrat de flux -> routes mortes) + Tier 1 (LLM conseil cost-aware : R4 + coherence semantique). Conseil/jamais bloquant. Valide sur le cockpit.',
    updatedAt: D(6, 21),
  },
  {
    id: 136,
    title: 'Bureau OS — interface iconique + fenetres superposables',
    status: 'done',
    model: 'opus',
    effort: 'L',
    tags: ['bureau-os', 'ui'],
    deps: [],
    notes: 'Refonte navigation COMPLETE P0->P4 : dock epure + Launcher, toute app = une fenetre du WindowManager, rail workspace facon VS Code, ecran Reglages unique. Palette systeme iOS/Apple.',
    updatedAt: D(6, 21),
  },
  {
    id: 99,
    title: 'Perfect Plan — questionnaire guide + dossier references',
    status: 'done',
    model: 'sonnet',
    effort: 'L',
    tags: ['cadrage', 'plan'],
    deps: [],
    notes: 'Avant le 1er prompt : (1) questionnaire 5 questions (type/style/nav/donnees/ambiance), (2) dossier refs (URLs Sharingan + palette + notes). Contrat contraignant injecte dans le system prompt.',
    updatedAt: D(6, 18),
  },
  {
    id: 105,
    title: 'MangoQA — framework d\'audit autonome (Production Aveugle / Audit Fantome)',
    status: 'done',
    model: 'opus',
    effort: 'XL',
    tags: ['mangoqa', 'infra'],
    deps: [],
    notes: 'Repo separe, process Node independant. 6 branches d\'audit en parallele + detection par sentinelle. Cycle complet valide (build -> Feu Rouge -> correction -> Feu Vert).',
    updatedAt: D(6, 19),
  },
  {
    id: 73,
    title: 'L\'armee automatique — patrouilleurs specialises auto-convoques',
    status: 'done',
    model: 'opus',
    effort: 'L',
    tags: ['agents', 'audit'],
    deps: [],
    notes: '5 patrouilleurs convoques par detection de contexte : Accessibilite · Securite · SEO · Performance · Bundle. Module patrol.ts, reveille fire-and-forget apres chaque tour. 33/33 tests.',
    updatedAt: D(6, 16),
  },
  {
    id: 75,
    title: 'Memoire procedurale — magasin .procedures/',
    status: 'done',
    model: 'sonnet',
    effort: 'L',
    tags: ['memoire', 'apprentissage'],
    deps: [],
    notes: 'Schemas de resolution (situation -> raisonnement -> pieges -> etapes validees) recuperes par similarite semantique (embeddings Ollama + cosinus, seuil 0.65). Skill=code · axiome=regle · procedure=demarche.',
    updatedAt: D(6, 16),
  },
  {
    id: 32,
    title: 'Boucle d\'entrainement nocturne',
    status: 'done',
    model: 'sonnet',
    effort: 'M',
    tags: ['nocturne', 'apprentissage'],
    deps: [],
    notes: 'CLI autonome : genere en boucle des creations diverses pendant que Raf dort (Eleve local $0, escalade Claude plafonnee). Remplit la courbe d\'apprentissage + genere des axiomes. 3600 combos.',
    updatedAt: D(6, 14),
  },
]
